---
title: "WHAT MAKES A GREAT JAMES BOND MOVIE?"
author: "Kacper Dobek"
date: "2022-08-08"
output: 
    html_document:
        css: "resources/style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(HoRM)
library(dplyr)
library(knitr)
library(DALEX)
library(caret)
library(h2o)
library(ggplot2)
library(corrplot)
set.seed(007)
```

## Getting the data

```{r dataprep}
data(JamesBond)
df <- JamesBond %>% select(-US_Gross, -World_Gross, -US_Adj, -Budget, -Avg_User_Rtn_Tom) %>%
  relocate(Avg_User_IMDB, .after = last_col())
kable(df)
```

## Including Plots

You can also embed plots, for example:

```{r martinis, echo=FALSE}
g <- ggplot(JamesBond, aes(Martinis, Movie)) + geom_point()
g

```

```{r corr}

df %>% select(-Movie, -Bond,) %>%
  cor()%>% 
  corrplot()
```

```{r automldef}

h2o.init()

h2o.no_progress()
target <- "Avg_User_IMDB"
df <- df %>% select(-Movie, -Bond) %>% as.h2o()



```


```{r automlmod}

model <- h2o.automl(y= target, training_frame = df, max_runtime_secs = 30, max_models = 5, nfolds = 10)
leader_board <- h2o.get_leaderboard(model)
head(leader_board)

```

```{r caret}

data(JamesBond)
df <- JamesBond %>% select(-Movie, -US_Gross, -World_Gross, -US_Adj, -Budget, -Avg_User_Rtn_Tom) %>%
  relocate(Avg_User_IMDB, .after = last_col())

train_control <- trainControl(method = "cv", number = 8, savePredictions = "all")

model_rf <- train(Avg_User_IMDB~. , data = df, method = "rf", ntree = 100, trControl = train_control)

explainer_rf <- DALEX::explain(model = model_rf,
                              label = "rf",
                              verbose = FALSE,
                              y = df$Avg_User_IMDB
                              )

print(model_performance(explainer_rf))


plot(model_parts(explainer_rf, loss_function = loss_root_mean_square))
```
```{r breakdown}
no_time_to_die <- data.frame(2021, "Daniel Craig", 608510000, 214930000, 163, 0, 1, 1, 66, 109, 1, 0)
colnames(no_time_to_die) <- colnames(df)
df <- rbind(df, no_time_to_die)

kable(no_time_to_die)

predict(explainer_rf, tail(df, n=1))

pb = predict_parts(explainer = explainer_rf, tail(df, n=1), type= "break_down")
plot(pb)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Resources

James Bond R dataset https://search.r-project.org/CRAN/refmans/HoRM/html/JamesBond.html

Daniel Craig's retrospective https://youtu.be/2oZdJrph3RA

